### PR TITLE
Integrate auth0-spa-js

### PR DESCRIPTION
**Pull request by stevehobbsdev**
This PR migrates from `auth0-js` to `auth0-spa-js`. It also implements some developer feedback, mostly around refactoring some components. This refactors both sample 01 and 03.

Key points:

* `authService.js` is refactored to use the new SDK. This has been influenced by the design of [the React wrapper](https://github.com/auth0-samples/auth0-react-samples/blob/master/01-Login/src/react-auth0-spa.js) and can similarly be extracted out into its own library in the future.
* `authGuard.js` is a new thing that protects routes from unauthenticated access. This can similarly be extracted out into the wrapper library

**Merging of this PR should be done in tandem with the associated documentation, which is not available yet**.

### CODE REVIEW

**Comment by nicbavetta** [comment]
Any idea when this will be reviewed/approved, merged, and supported with QuickStart documentation?

**Comment by luisrudge** [comment]
@nicbavetta the sample is good to go. We're just waiting for another internal review from someone that has more experience with real world vue apps. 

The actual docs/quickstarts will take a bit more time though, no ETA yet.

**Comment by nicbavetta** [comment]
> @nicbavetta the sample is good to go. We're just waiting for another internal review from someone that has more experience with real world vue apps.
> 
> The actual docs/quickstarts will take a bit more time though, no ETA yet.

Awesome, thanks for the quick response. The source code is enough - the documentation is just icing on the cake. :)

**Comment by stevehobbsdev** [comment]
This PR has been merged locally and pushed 🎉

**Pull request closed without merging**
