### PR TITLE
Changes for consistency between samples

### PR DESCRIPTION
**Pull request by omar-compres**
Modifying the 'serve' command to also run the backend. This way, it is consistent with what is shown on the sample download instructions.

### CODE REVIEW

**Comment by stevehobbsdev** [comment]
Thanks @omar-compres. Can you also link the relevant changeset from the Docs project too?

**Comment by omar-compres** [comment]
Hey @stevehobbsdev, this is what is related to this changeset from the Docs project: [https://github.com/auth0/docs/pull/8432](url)

**Comment by stevehobbsdev** [comment]
Thanks @omar-compres.

We should also probably remove the `dev` command from `package.json` as it's now duplicated by the `serve` command. Also, you'll need to update the README file to show `npm run serve` instead of `npm run dev` underneath the "Running in development" heading.

**Comment by omar-compres** [comment]
Thanks @stevehobbsdev. The suggested changes were also included.

**Pull request merged**
